on: [push]

jobs:
  deploy_check_job:
    runs-on: ubuntu-latest
    name: Analyse Source Code with PMD

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Generate report
      - name: Generate PMD report
        id: generate-pmd-report
        uses: uses: docker://rawdee/pmd:latest
        with:
          args:
            dir: '.'
            rulesets: 'rulesets/apex/quickstart'
