name: Analyse Source Code
on: [push]

jobs:
analysis:
  name: Analysis
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PMD Report
      uses: rody/pmd-github-action@main
      with:
        rulesets: 'rulesets/apex/quickstart.xml'
        reportfile: 'pmd-report.json'
        format: 'json'
        failOnViolation: 'false'

    - name: Create PMD annotations
      uses: rody/pmd-annotations-github-action@main
      with:
        reportfile: 'pmd-report.json'
