name: validate-apex-code
on: [push]
jobs:
  check-apex:
    runs-on: ubuntu-latest
    steps:
      - name: Check APEX
        uses: legetz/setup-pmd@v6.48
      - run: echo --dir
      - run: echo pwd
      - run: echo ls
      - run: pwd
      - run: echo --dir
