name: validate-apex-code
on: [push]
jobs:
  check-apex:
    runs-on: ubuntu-latest
    steps:
      - name: Check APEX
        uses: legetz/setup-pmd@v6.48
      - run: pwd
      - run: cd ..
      - run: pwd
      - run: ls -a
      - run: ls -la
