steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
  - uses: legetz/setup-pmd@v6.48
    with:
      distribution: 'temurin'
      java-version: '11'
  - uses: pmd/pmd-github-action@v1
    id: pmd
    with:
      sourcePath: 'src/main/apex'
      rulesets: 'rulesets/apex/quickstart.xml,ruleset.xml'
